name: Deploy to Surge

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install Surge
        run: npm install --global surge
      
      - name: Deploy to Surge
        uses: surge/add-static-site@latest
        with:
          project: build
          domain: versed-clock.surge.sh
          token: ${{ secrets.SECRETS_SURGE_TOKEN }}