name: Deploy to Surge

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Surge
        uses: surge/add-static-site@latest
        with:
          project: build
          domain: versed-clock.surge.sh
          token: ${{ SECRETS_SURGE_TOKEN }}